In [2]:
import pandas as pd 

In [3]:
df = pd.read_csv('weather_data.csv')

In [4]:
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [5]:
df.shape

(6, 4)

In [6]:
rows, columns = df.shape


In [7]:
rows

6

In [14]:
df.tail(2)

day  temperature  windspeed  event
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [15]:
df.head()

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [21]:
df[2:5]

day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

In [26]:
df.columns


Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [27]:
df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [28]:
df.event

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

In [29]:
df["temperature"]

0    32
1    35
2    28
3    24
4    32
5    31
Name: temperature, dtype: int64

In [30]:
type(df.event)

pandas.core.series.Series

In [31]:
type(df[:])

pandas.core.frame.DataFrame

In [35]:
df[["event","day"]]

event       day
0   Rain  1/1/2017
1  Sunny  1/2/2017
2   Snow  1/3/2017
3   Snow  1/4/2017
4   Rain  1/5/2017
5  Sunny  1/6/2017

In [36]:
df.temperature.max()

35

In [37]:
df["temperature"].min()

24

In [38]:
df.temperature

0    32
1    35
2    28
3    24
4    32
5    31
Name: temperature, dtype: int64

In [39]:
df.temperature.mean()

30.333333333333332

In [41]:
df.describe()

temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [47]:
df[df.temperature == 32]

day  temperature  windspeed event
0  1/1/2017           32          6  Rain
4  1/5/2017           32          4  Rain

In [48]:
type(df.temperature == 32)

pandas.core.series.Series

In [52]:
list1 = {"list":[True,False,False,True,False,False]}

In [54]:
lis = pd.DataFrame(list1)

In [60]:
lis.list
df[lis.list]


day  temperature  windspeed event
0  1/1/2017           32          6  Rain
3  1/4/2017           24          7  Snow

In [56]:
df[lis]

day  temperature  windspeed event
0  NaN          NaN        NaN   NaN
1  NaN          NaN        NaN   NaN
2  NaN          NaN        NaN   NaN
3  NaN          NaN        NaN   NaN
4  NaN          NaN        NaN   NaN
5  NaN          NaN        NaN   NaN

In [61]:
df.temperature == df.temperature.max()

0    False
1     True
2    False
3    False
4    False
5    False
Name: temperature, dtype: bool

In [67]:
df[df.temperature == df.temperature.max()]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [68]:
df["day"][df.temperature == df.temperature.max()]

1    1/2/2017
Name: day, dtype: object

In [73]:
df[["day","event","temperature"]][df.temperature == df.temperature.max()]

day  event  temperature
1  1/2/2017  Sunny           35

In [78]:
df_se = pd.Series(df.temperature)

In [79]:
df_se


0    32
1    35
2    28
3    24
4    32
5    31
Name: temperature, dtype: int64

In [81]:
df_se.index

RangeIndex(start=0, stop=6, step=1)

In [82]:
df.temperature.index

RangeIndex(start=0, stop=6, step=1)

In [83]:
df_se.array

<PandasArray>
[32, 35, 28, 24, 32, 31]
Length: 6, dtype: int64

In [84]:
kk = df_se.array
kk

<PandasArray>
[32, 35, 28, 24, 32, 31]
Length: 6, dtype: int64

In [85]:
df_se.values

array([32, 35, 28, 24, 32, 31], dtype=int64)

In [86]:
import numpy as np


In [87]:
arr = np.array(df_se.values)

In [88]:
arr

array([32, 35, 28, 24, 32, 31], dtype=int64)

In [89]:
arr.T

array([32, 35, 28, 24, 32, 31], dtype=int64)

In [90]:
arr[3]

24

In [91]:
arr2 = np.array([1,2,3,4,5,6])

In [92]:
arr + arr2

array([33, 37, 31, 28, 37, 37], dtype=int64)

In [93]:
arr2.dtype

dtype('int32')

In [94]:
df_se.nbytes

48